---
- name: Install Docker on Ubuntu 20.04
  hosts: localhost
  become: yes  # To run tasks with sudo

  tasks:
    - name: Update the package index
      apt:
        update_cache: yes
      become: yes

    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      become: yes

    - name: Add Docker's GPG key
      shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"
      become: yes

    - name: Set up the stable Docker repository
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        create: yes
      become: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      become: yes

    - name: Add your user to the Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: yes

    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted
        enabled: yes
      become: yes

    - name: Test Docker installation
      command: docker --version
